name: Documentation

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - run: cargo install trunk --locked

      - run: trunk build --release --public-url "/"
        working-directory: gui

      - uses: actions/upload-pages-artifact@v5
        with:
          path: gui/dist

      - uses: actions/deploy-pages@v5
        id: deployment
